[build]
  command = "cd netlify/functions && npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
